mysql.source:
  connector.class: "io.debezium.connector.mysql.MySqlConnector"
  tasks.max: "1"
  database.server.id: "184054"
  database.server.name: "dbserver1"
  database.history.kafka.bootstrap.servers: "kafka:9092"
  database.history.kafka.topic: "schema-changes.my_db"


#schema_registry_url: str = field(default_factory=str)
#key_converter_schema_registry_url: str = field(default_factory=str)
#value_converter_schema_registry_url: str = field(default_factory=str)
mysql.sink:
  topics_dir: "picpay_applications"
  tasks_max: "3"
  s3_bucket_name: "picpay-datalake-sandbox"
  s3_part_size: "134217728"
  flush_size: "35000"
  rotate_schedule_interval_ms: "180000"
  timezone: "UTC"
  partition_duration_ms: "600000"
  locale: "en-US"
  partitioner_class: "io.confluent.connect.storage.partitioner.TimeBasedPartitioner"
  path_format: "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH"
  parquet_codec: "snappy"
  connector_class: "io.confluent.connect.s3.S3SinkConnector"
  storage_class: "io.confluent.connect.s3.storage.S3Storage"
  format_class: "io.confluent.connect.s3.format.parquet.ParquetFormat"
  value_converter: "io.confluent.connect.avro.AvroConverter"
  key_converter: "io.confluent.connect.avro.AvroConverter"
  schema_compatibility: "BACKWARD"
  s3_region: "us-east-1"
  s3_credentials_provider_class: "com.amazonaws.auth.DefaultAWSCredentialsProviderChain"
  behavior_on_null_values: "ignore"




